config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :products , only: :index
  resources :orders , only: [:index, :destroy] do
    get 'items', to: 'orders#items', as: :products
  end
  resources :order_items, only: [:index, :create, :destroy], path: '/cart/items'

  get '/cart', to: 'order_items#index'
  get 'cart/checkout', to: 'orders#new', as: :checkout
  patch 'cart/checkout', to: 'orders#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items, class_name: 'OrderItem', :dependent => :delete_all

  enum status: %w{cart open delivered removed}
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
end

app/models/shopping_cart.rb
class ShoppingCart
  delegate :subtotal, to: :order

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by token: @token, status: Order.statuses[:cart] do |order|
      order.subtotal = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find product_id
    order_item = order.items.find_or_initialize_by product_id: product_id

    order_item.price = product.price
    order_item.quantity = quantity

    ActiveRecord::Base.transaction do
      order_item.save
      update_subtotal!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
      order.items.destroy(id)
      update_subtotal!
    end
  end

  private

  def update_subtotal!
    order.subtotal = order.items.sum('quantity * price')
    order.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_cart
    @current_cart ||= ShoppingCart.new token: cart_token
  end
  helper_method :current_cart

  def cart_token
    @cart_token unless @cart_token.nil?

    session[:cart_token] ||= SecureRandom.hex 8
    @cart_token = session[:cart_token]
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
    @items = current_cart.order.items
  end

  def create
    current_cart.add_item(
      product_id: params[:product_id],
      quantity: params[:quantity]
    )

    redirect_to cart_path
  end

  def destroy
    current_cart.remove_item(id: params[:id])
    redirect_to cart_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(status: Order.statuses[:open])
  end

  def new
    @order = current_cart.order
  end

  def items
    @order = Order.find params[:order_id]
    # @items = OrderItem.where order_id: params[:order_id]
  end
  def create
    @order = current_cart.order

    if @order.update_attributes(order_params.merge(status: Order.statuses[:open]))
      session[:cart_token] = nil
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    Order.destroy params[:id]
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @message = ''
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Ecommerce
      = Rails.env unless Rails.env.production?
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = csp_meta_tag

  %body{ data: { controller: params[:controller], action: params[:action] } }
    .public-access
      .generic-header
      .container-fluid
        = render 'shared/header'
        - if notice.present? || alert.present?
          .alert.alert-dismissible{role: :alert, class: notice.present? ? "alert-success" : "alert-danger"}
            %button.close{type: :button, data: {dismiss: :alert}, aria: {label: 'Close'}}
              %span{aria: {hidden: "true"}} &times;
            = notice || alert
        = yield

    -# = yield :sidebar

    / JS files
    = javascript_include_tag 'application'

app/views/order_items/index.html.haml
%strong.code#message= @message

%h4
  %strong Current Cart
%table.table.table-striped
  %thead
    %tr
      %td
        %strong Product
      %td
        %strong Price
      %td
        %strong Quantity
      %td
  %tbody
    - @items.each do |item|
      %tr.table-row
        %td= item.product.title
        %td= number_to_currency item.price
        %td= item.quantity
        %td
          = form_for item, class: "form-inline", method: :delete do |f|
            .form-row.align-items-center
              = f.submit 'Remove', class: 'add-item btn btn-danger mb-1'

  %tfoot
    %tr
      %td Subtotal
      %td= number_to_currency current_cart.order.subtotal

= link_to 'Checkout', checkout_path, class: 'btn btn-success' unless current_cart.order.subtotal == 0

app/views/orders/index.html.haml
%strong.code#message= @message
%h4
  %strong Orders
%table.table.table-striped
  %thead
    %tr
      %td
        %strong Order
      %td
        %strong First Name
      %td
        %strong Last Name
      %td
        %strong Status
      %td
        %strong Subtotal
      %td
  %tbody
    - @orders.each do |order|
      %tr.table-row
        %td= order.token
        %td= order.first_name
        %td= order.last_name
        %td= order.status
        %td= number_to_currency order.subtotal
        %td
          = link_to 'Items', order_products_path(order.id), class: 'btn btn-warning'
          = form_for order, class: "form-inline", method: :delete do |f|
            .form-row.align-items-center
              = f.submit 'Remove', class: 'add-item btn btn-danger mb-1'

app/views/orders/items.html.haml
%strong.code#message= @message

%h4
  %strong Order Items
%table.table.table-striped
  %thead
    %tr
      %td
        %strong Product
      %td
        %strong Price
      %td
        %strong Quantity
  %tbody
    - @order.items.each do |item|
      %tr.table-row
        %td= item.product.title
        %td= number_to_currency item.price
        %td= item.quantity

  %tfoot
    %tr
      %td Subtotal
      %td= number_to_currency @order.subtotal

= link_to 'Back', :back, class: 'btn btn-warning'

app/views/orders/new.html.haml
%h2 Checkout

= form_for @order, url: checkout_path do |f|
  .form-group
    = f.label :first_name
    = f.text_field :first_name
  .form-group
    = f.label :last_name
    = f.text_field :last_name

  = f.submit 'Checkout', class: 'btn btn-success'

app/views/products/index.html.haml
%strong.code#message= @message
%h4
  %strong E-Commerce
%table.table.table-striped
  %thead
    %tr
      %td
        %strong Product
      %td
        %strong Price
      %td
        %strong Buy
  %tbody
    - @products.each do |product|
      %tr.table-row
        %td= product.title
        %td= number_to_currency product.price
        %td
          = form_tag order_items_path, class: "form-inline" do
            .form-row.align-items-center
              = hidden_field_tag :product_id, product.id
              = number_field_tag :quantity, 1, min: 1, class: 'form-control mb-1'
              = submit_tag 'Add to cart', class: 'add-item btn btn-primary mb-1'

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %a.navbar-brand{:href => "#"} E-Commerce
    %ul.nav.navbar-nav
      %li.active
        = link_to 'Home', root_path
      %li
        = link_to 'Cart', cart_path
      %li
        = link_to 'Orders', orders_path
    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to cart_path do
          %i.glyphicon.glyphicon-shopping-cart
          %span.badge.badge-pill.badge-success= current_cart.items_count